### ISSUE TITLE
RPi 5, Ubuntu 23.10, Command '['vcgencmd', 'measure_temp']' returned non-zero exit status 255.

### ISSUE THREAD

**Issue by InfiniteBSOD** [nschloe/stressberry#136]
Raspberry Pi 5 8GB
Case: Argon NEO 5 BRED
PSU: Official RPi 5 PSU
OS: Ubuntu 23.10 aarch64 
Kernel: 6.5.0-1009-raspi 

Hello,

Trying to run "stressberry" on my new RPi 5 8GB running Ubuntu 23.10 but I get the following error (see below).
I am not that well versed in Linux, simply followed the commands here:
[](https://www.makeuseof.com/raspberry-pi-5-overclocking-guide/)
and currently running with the following OC:
```
[custom]

# Tell the DVFS algorithm to increase voltage by this amount (in µV; default 0).
# IMPORTANT: See note below
over_voltage_delta=50000

# Set the Arm A76 core frequency (in MHz; default 2400).
arm_freq=2900

# Set the VideoCore VII core frequency (in MHz; default 800).
gpu_freq=900

```

Would like to gradually up the "arm_freq" since 3000/1000, 3000/950 , 2950/950 failed to boot but 2950/900 allowed me to boot but first wanted to stresstest my current OC.

```
cat /sys/class/thermal/thermal_zone0/temp
48500
```

The error I'm receiving:

```
(overclock) rpi5@ubuntu:~/overclock$ stressberry-run -n "My Test" -d 100 -i 30 -c 4 mytest1.dat
Awaiting stable baseline temperature...
Traceback (most recent call last):
  File "/home/rpi5/overclock/bin/stressberry-run", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/home/rpi5/overclock/lib/python3.11/site-packages/stressberry/cli/run.py", line 92, in run
    cooldown(interval=args.cooldown, filename=args.temperature_file)
  File "/home/rpi5/overclock/lib/python3.11/site-packages/stressberry/main.py", line 13, in cooldown
    prev_tmp = measure_temp(filename=filename)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rpi5/overclock/lib/python3.11/site-packages/stressberry/main.py", line 34, in measure_temp
    out = subprocess.check_output(["vcgencmd", "measure_temp"]).decode("utf-8")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['vcgencmd', 'measure_temp']' returned non-zero exit status 255.
(overclock) rpi5@ubuntu:~/overclock$ stressberry -run -n "My Test" -d 100 -i 30 -c 4 mytest1.dat
stressberry: command not found
(overclock) rpi5@ubuntu:~/overclock$ stressberry-run -n "My Test" -d 100 -i 30 -c 4 mytest1.dat
Awaiting stable baseline temperature...
Traceback (most recent call last):
  File "/home/rpi5/overclock/bin/stressberry-run", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/home/rpi5/overclock/lib/python3.11/site-packages/stressberry/cli/run.py", line 92, in run
    cooldown(interval=args.cooldown, filename=args.temperature_file)
  File "/home/rpi5/overclock/lib/python3.11/site-packages/stressberry/main.py", line 13, in cooldown
    prev_tmp = measure_temp(filename=filename)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rpi5/overclock/lib/python3.11/site-packages/stressberry/main.py", line 34, in measure_temp
    out = subprocess.check_output(["vcgencmd", "measure_temp"]).decode("utf-8")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['vcgencmd', 'measure_temp']' returned non-zero exit status 255.
(overclock) rpi5@ubuntu:~/overclock$ stressberry-run -n "My Test" -d 100 -i 30 -c 4 mytest2.dat
Awaiting stable baseline temperature...
Traceback (most recent call last):
  File "/home/rpi5/overclock/bin/stressberry-run", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/home/rpi5/overclock/lib/python3.11/site-packages/stressberry/cli/run.py", line 92, in run
    cooldown(interval=args.cooldown, filename=args.temperature_file)
  File "/home/rpi5/overclock/lib/python3.11/site-packages/stressberry/main.py", line 13, in cooldown
    prev_tmp = measure_temp(filename=filename)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rpi5/overclock/lib/python3.11/site-packages/stressberry/main.py", line 34, in measure_temp
    out = subprocess.check_output(["vcgencmd", "measure_temp"]).decode("utf-8")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['vcgencmd', 'measure_temp']' returned non-zero exit status 255.
```

Appreciate your work / InfiniteBSOD

**Comment by kuchidareo** [comment]
I encountered the same problem.
I resolved it by adding the video group to the user.
Look at [this blog](https://helloraspberrypi.blogspot.com/2020/11/run-vcgencmd-on-ubuntu-for-raspberry-pi.html)
