### ISSUE TITLE
Broken?!

### ISSUE THREAD

**Issue by Dan1jel** [nschloe/stressberry#15]
I've installed both but I just get an error. So it's more then just install two things apperently. 

This is what I got:
```
~ $ MPLBACKEND=Agg stressberry-plot out.dat -o out.png


Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/numpy/core/__init__.py", line 16,
 in <module>
    from . import multiarray
ImportError: libf77blas.so.3: cannot open shared object file: No such file or di
rectory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/stressberry-plot", line 7, in <module>
    from stressberry.cli import plot
  File "/usr/local/lib/python3.5/dist-packages/stressberry/__init__.py", line 15
, in <module>
    from . import cli
  File "/usr/local/lib/python3.5/dist-packages/stressberry/cli.py", line 8, in <
module>
    import matplotlib.pyplot as plt
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/__init__.py", line 126
, in <module>
    from . import cbook
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/cbook/__init__.py", li
ne 34, in <module>
    import numpy as np
  File "/usr/local/lib/python3.5/dist-packages/numpy/__init__.py", line 142, in
<module>
    from . import add_newdocs
  File "/usr/local/lib/python3.5/dist-packages/numpy/add_newdocs.py", line 13, i
n <module>
    from numpy.lib import add_newdoc
  File "/usr/local/lib/python3.5/dist-packages/numpy/lib/__init__.py", line 8, i
n <module>
    from .type_check import *
  File "/usr/local/lib/python3.5/dist-packages/numpy/lib/type_check.py", line 11
, in <module>
    import numpy.core.numeric as _nx
  File "/usr/local/lib/python3.5/dist-packages/numpy/core/__init__.py", line 26,
 in <module>
    raise ImportError(msg)
ImportError:
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: libf77blas.so.3: cannot open shared object file: No such fil
e or directory
```

**Comment by nschloe** [comment]
```
ImportError: libf77blas.so.3: cannot open shared object file: No such file or directory
```
Seems like a broken installation.

**Comment by Naphier** [comment]
Atlas needs to be installed.
`sudo apt-get install libatlas-base-dev`
But after this I get a new error. Will open a ticket.

**Comment by wupasscat** [comment]
after installing atlas, this happens: 

ImportError: cairo backend requires that cairocffi or pycairo is installed
How do I fix this and why does the installation have to be so complicated!

**Comment by nschloe** [comment]
@wupasscat If you have a problem, please open a new issue. Otherwise, everyone in this thread will be spammed.

> after installing atlas, this happens:

When you do what exactly?

```
ImportError: cairo backend requires that cairocffi or pycairo is installed
```
Are you running it without a graphical user interface? Then you probable require
```
MPLBACKEND=Agg stressberry-plot out.dat -o out.png
```
(See main README.)
