### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'plot'

### ISSUE THREAD

**Issue by pythonpadawanEXE** [nschloe/stressberry#44]
```
pi@raspberrypi:~ $ MPLBACKEND=Agg stressberry-plot out.dat 
Traceback (most recent call last):
  File "/home/pi/.local/bin/stressberry-plot", line 10, in <module>
    sys.exit(plot())
  File "/home/pi/.local/lib/python3.7/site-packages/stressberry/cli.py", line 152, in plot
    ax1.plot(
AttributeError: 'NoneType' object has no attribute 'plot'
```
I have limited knowledge of linux and I'm not sure how to fix this error, I already have a plot file with the out data which i got from the first command . Thanks for all your help this is a great little project.

**Comment by nschloe** [comment]
Same as #42. This is a broken installation, some people fixed it by
```
pip3 install -U matplotlib
```
