### ISSUE TITLE
Error after 150s idle phase

### ISSUE THREAD

**Issue by 3Domse3** [nschloe/stressberry#76]
Shell output after 150s idle phase (RPi 3b, no overclock, clean Buster without any tweaks etc.)
:
`Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/stressberry/cli/run.py", line 96, in <lambda>
    target=lambda: test(args.duration, args.idle, args.cores), args=()
  File "/home/pi/.local/lib/python3.7/site-packages/stressberry/main.py", line 99, in test
    stress_cpu(num_cpus=cores, time=stress_duration)
  File "/home/pi/.local/lib/python3.7/site-packages/stressberry/main.py", line 7, in stress_cpu
    subprocess.check_call(["stress", "--cpu", str(num_cpus), "--timeout", f"{time}s"])
  File "/usr/lib/python3.7/subprocess.py", line 342, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.7/subprocess.py", line 323, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'stress': 'stress'`

**Comment by nschloe** [comment]
```
No such file or directory: 'stress': 'stress'
```
You need `stress` installed. https://github.com/nschloe/stressberry#how-to
