### ISSUE TITLE
ImportError: libf77blas.so.3: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Peemouse** [nschloe/stressberry#83]
Hi,
Thanks for the tool.
I followed the instructions for running a stress test, but when I issue the command
`MPLBACKEND=Agg stressberry-plot out.dat -o out.png`
or
`stressberry-plot out.dat -o out.png`

I get this error :

```
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/numpy/core/__init__.py", line 22, in <module>
    from . import multiarray
  File "/home/pi/.local/lib/python3.7/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/home/pi/.local/lib/python3.7/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: libf77blas.so.3: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/bin/stressberry-plot", line 10, in <module>
    sys.exit(plot())
  File "/home/pi/.local/lib/python3.7/site-packages/stressberry/cli/plot.py", line 9, in plot
    import dufte
  File "/home/pi/.local/lib/python3.7/site-packages/dufte/__init__.py", line 2, in <module>
    from .main import legend, style
  File "/home/pi/.local/lib/python3.7/site-packages/dufte/main.py", line 3, in <module>
    import matplotlib as mpl
  File "/home/pi/.local/lib/python3.7/site-packages/matplotlib/__init__.py", line 107, in <module>
    from . import cbook, rcsetup
  File "/home/pi/.local/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 28, in <module>
    import numpy as np
  File "/home/pi/.local/lib/python3.7/site-packages/numpy/__init__.py", line 140, in <module>
    from . import core
  File "/home/pi/.local/lib/python3.7/site-packages/numpy/core/__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.7 from "/usr/bin/python3"
  * The NumPy version is: "1.19.1"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: libf77blas.so.3: cannot open shared object file: No such file or directory
```

I'm using a Raspberry Pi 4 2Gb running Retropie 4.6.6 (Raspbian GNU/Linux 10 (buster))

**Comment by Peemouse** [comment]
Going on https://numpy.org/devdocs/user/troubleshooting-importerror.html
made me issuing this command 
`sudo apt-get install libatlas-base-dev`

Then, trying `stressberry-run out.dat` worked fine. 👍 

Maybe add this tip in the README for others users who may encounter the same issue ?
Thanks !
