### ISSUE TITLE
ImportError: No module named functools_lru_cache

### ISSUE THREAD

**Issue by danielktdoranie** [nschloe/stressberry#94]
So this is happening, first install and attempted run. Halp pls. KTHXBYE.

> pi@raspberrypi:~ $ stressberry-run out.dat
Traceback (most recent call last):
  File "/usr/local/bin/stressberry-run", line 6, in <module>
    from stressberry.cli import run
  File "/usr/local/lib/python2.7/dist-packages/stressberry/__init__.py", line 15, in <module>
    from . import cli
  File "/usr/local/lib/python2.7/dist-packages/stressberry/cli.py", line 8, in <module>
    import matplotlib.pyplot as plt
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/__init__.py", line 133, in <module>
    from matplotlib.rcsetup import defaultParams, validate_backend, cycler
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/rcsetup.py", line 31, in <module>
    from matplotlib.fontconfig_pattern import parse_fontconfig_pattern
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/fontconfig_pattern.py", line 28, in <module>
    from backports.functools_lru_cache import lru_cache
**ImportError: No module named functools_lru_cache**

Running this on a Raspberry Pi 4 Model B 8 GB

![Screenshot from 2021-01-31 00-20-35](https://user-images.githubusercontent.com/69985694/106371252-2ee68d80-635a-11eb-9b5e-ccd29f33a3bd.png)

![download](https://user-images.githubusercontent.com/69985694/106371260-50e01000-635a-11eb-887d-6c2250a56193.png)

**Comment by nschloe** [comment]
Nice cat. You're using Python 2 which is is over ten years old. See https://github.com/nschloe/stressberry/issues/100.
